**Exercice 1 : Introduction à l'analyse des données (Facile)**

1) Qu'est-ce que l'analyse de données ?

*L'analyse de données est le processus d'examiner, de nettoyer, de transformer et de modéliser des données dans le but de découvrir des informations utiles, de tirer des conclusions et de soutenir la prise de décision. Elle implique l'utilisation de diverses techniques statistiques, algorithmiques et visuelles pour interpréter les données et en extraire des insights significatifs.*

2) Pourquoi l'analyse des données est-elle importante dans les contextes modernes ?

*Elle est importante car elle permet aux organisations de prendre des décisions éclairées, d'identifier des tendances, d'améliorer les processus et de rester compétitives dans un monde de plus en plus axé sur les données.*

3) Citez et décrivez trois domaines d'application actuels de l'analyse de données.

*la santé : L'analyse de données est utilisée pour améliorer les diagnostics, personnaliser les traitements et optimiser les opérations hospitalières.*

*la finance : Les institutions financières utilisent l'analyse de données pour la détection de fraudes, la gestion des risques et l'optimisation des portefeuilles d'investissement.*

*le marketing : Les entreprises exploitent l'analyse de données pour comprendre le comportement des consommateurs, segmenter les marchés et personnaliser les campagnes publicitaires.*

------------

**Exercice 2 : Chargement et analyse initiale des données**

*Chargez l'ensemble de données*

In [1]:
#Importer Pandas
import pandas as pd

In [ ]:
#Chargement des données df1
df1 = pd.read_csv("Time Americans Spend Sleeping.csv")

In [7]:
#Chargement des données df2
df2 = pd.read_csv("Mental_health_Depression_disorder_Data.csv")

C:\Users\USER\AppData\Local\Temp\ipykernel_18744\780387165.py:2: DtypeWarning: Columns (0: Bipolar disorder (%), 1: Eating disorders (%)) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("Mental_health_Depression_disorder_Data.csv")

In [8]:
#Chargement des données df3 ET df4
df3 = pd.read_csv("clean_dataset.csv")

df4 = pd.read_csv("crx.csv")

*Afficher les premières lignes*

In [ ]:
#Données df1
df1.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [9]:
#données df2
df2.head()

,index,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
0,0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

In [10]:
#Données DF3
df3.head()

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

In [11]:
#Données df4
df4.head()

   b  30.83      0  u  g  w  v  1.25  t t.1  01  f g.1  00202  0.1  +
0  a  58.67  4.460  u  g  q  h  3.04  t   t   6  f   g  00043  560  +
1  a  24.50  0.500  u  g  q  h  1.50  t   f   0  f   g  00280  824  +
2  b  27.83  1.540  u  g  w  v  3.75  t   t   5  t   g  00100    3  +
3  b  20.17  5.625  u  g  w  v  1.71  t   f   0  f   s  00120    0  +
4  b  32.08  4.000  u  g  m  v  2.50  t   f   0  t   g  00360    0  +

*Une brève description de l'ensemble de données*

Ce que nous pouvons dire de ces données que avons chargé,  Les données sont propres et ne contiennent pas de valeurs manquantes dans la plus par des datasets. Les types de données sont appropriés pour l'analyse.

------

**Exercice 3 : Identification des types de données**

Pour les ensembles de données de l'exercice précédent, catégorisez chaque colonne comme quantitative ou qualitative et expliquez votre raisonnement.

In [28]:
#classer les colonnes qualitatives et quantitatives de df1
qualitative_df1 = df1.select_dtypes(include=['object']).columns

quantitatives_df1 = df1.select_dtypes(include=['number']).columns

print("Colonnes qualitatives de df1 : ", qualitative_df1)
print("Colonnes quantitatives de df1 : ", quantitatives_df1)

Colonnes qualitatives de df1 :  Index(['Period', 'Type of Days', 'Age Group', 'Activity', 'Sex'], dtype='str')
Colonnes quantitatives de df1 :  Index(['index', 'Year', 'Avg hrs per day sleeping', 'Standard Error'], dtype='str')

C:\Users\USER\AppData\Local\Temp\ipykernel_18744\2674919443.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  qualitative_df1 = df1.select_dtypes(include=['object']).columns

In [29]:
#classer les colonnes qualitatives et quantitatives de df2
qualitative_df2 = df2.select_dtypes(include=['object']).columns

quantitatives_df2 = df2.select_dtypes(include=['number']).columns

print("Colonnes qualitatives de df2 : ", qualitative_df2)
print("Colonnes quantitatives de df2 : ", quantitatives_df2)

Colonnes qualitatives de df2 :  Index(['Entity', 'Code', 'Year', 'Schizophrenia (%)', 'Bipolar disorder (%)',
       'Eating disorders (%)'],
      dtype='str')
Colonnes quantitatives de df2 :  Index(['index', 'Anxiety disorders (%)', 'Drug use disorders (%)',
       'Depression (%)', 'Alcohol use disorders (%)'],
      dtype='str')

C:\Users\USER\AppData\Local\Temp\ipykernel_18744\3523573734.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  qualitative_df2 = df2.select_dtypes(include=['object']).columns

In [30]:
#classer les colonnes qualitatives et quantitatives de df3
qualitative_df3 = df3.select_dtypes(include=['object']).columns

quantitatives_df3 = df3.select_dtypes(include=['number']).columns

print("Colonnes qualitatives de df3 : ", qualitative_df3)
print("Colonnes quantitatives de df3 : ", quantitatives_df3)

Colonnes qualitatives de df3 :  Index(['Industry', 'Ethnicity', 'Citizen'], dtype='str')
Colonnes quantitatives de df3 :  Index(['Gender', 'Age', 'Debt', 'Married', 'BankCustomer', 'YearsEmployed',
       'PriorDefault', 'Employed', 'CreditScore', 'DriversLicense', 'ZipCode',
       'Income', 'Approved'],
      dtype='str')

C:\Users\USER\AppData\Local\Temp\ipykernel_18744\838740637.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  qualitative_df3 = df3.select_dtypes(include=['object']).columns

In [31]:
#classer les colonnes qualitatives et quantitatives de df4
qualitative_df4 = df1.select_dtypes(include=['object']).columns

quantitatives_df4 = df1.select_dtypes(include=['number']).columns

print("Colonnes qualitatives de df4 : ", qualitative_df4)
print("Colonnes quantitatives de df4 : ", quantitatives_df4)

Colonnes qualitatives de df4 :  Index(['Period', 'Type of Days', 'Age Group', 'Activity', 'Sex'], dtype='str')
Colonnes quantitatives de df4 :  Index(['index', 'Year', 'Avg hrs per day sleeping', 'Standard Error'], dtype='str')

C:\Users\USER\AppData\Local\Temp\ipykernel_18744\1254140892.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  qualitative_df4 = df1.select_dtypes(include=['object']).columns

---------

**Exercice 4 : Exploration des types de données**

*chargement du jeu de données iris*

In [14]:
#Charger le jeu de données iris
iris =  pd.read_csv("Iris.csv")

In [15]:
#affichage des premières lignes du jeu de données iris
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

*Identifiez et listez les colonnes qualitatives et quantitatives de votre ensemble de données*

In [ ]:
# les colonnes qualitatives des données
qualitative_clos = iris.select_dtypes(include=['object']).columns
print("Colonnes qualitatives : ", qualitative_clos)

Colonnes qualitatives :  Index(['Species'], dtype='str')

C:\Users\USER\AppData\Local\Temp\ipykernel_18744\3628642110.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  qualitative_clos = iris.select_dtypes(include=['object']).columns

In [23]:
#Données quantitatives
quantitative_clos = iris.select_dtypes(include=['number']).columns
print("Colonnes quantitatives : ", quantitative_clos)

Colonnes quantitatives :  Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'], dtype='str')

*pourquoi chaque colonne est classée comme qualitative ou quantitative?*

Les colonnes qualitatives contiennent des données catégorielles, telles que des noms ou des catégories, tandis que les colonnes quantitatives contiennent des données numériques qui peuvent être mesurées et ordonnées.

------------

**Exercice 5 : Compétences de base en observation et analyse de données**

*Charger les données*

In [27]:
#importer la bibliothèque pandas
import pandas as pd

In [28]:
#Charger les données
sleep = pd.read_csv("Time Americans Spend Sleeping.csv")

sleep.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [29]:
sleep.info()

<class 'pandas.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     945 non-null    int64
 1   Year                      945 non-null    int64
 2   Period                    945 non-null    str
 3   Avg hrs per day sleeping  945 non-null    float64
 4   Standard Error            945 non-null    float64
 5   Type of Days              945 non-null    str
 6   Age Group                 945 non-null    str
 7   Activity                  945 non-null    str
 8   Sex                       945 non-null    str
dtypes: float64(2), int64(2), str(5)
memory usage: 66.6 KB

*Identifiez les colonnes potentiellement pertinentes pour un type d'analyse spécifique*

identifications des potentielles colonnes pertinentes

*Les colonnes pertinentes sont les suivantes : "Avg hrs per day sleeping", "Age Group*

-----------

**Exercice 6 : Identification des types de données**

- Les rapports financiers d'une entreprise sont stockés dans un fichier Excel: ces types de données sont structurés, car ils sont organisés en lignes et en colonnes avec des étiquettes pour chaque type de données.

- Photographies téléchargées sur une plateforme de médias sociaux : ces types de données sont non structurés, car ils ne suivent pas un format pré-défini ou ne sont pas organisés de manière systématique.

- Une collection d'articles de presse sur un site web: ces données peuvent être structurées si elles sont organisées avec des métadonnées (titre, auteur, date), mais elles peuvent aussi être non structurées si elles sont simplement du texte brut sans organisation claire.

- Données d'inventaire dans une base de données relationnelle: ces données sont structurées, car elles sont organisées en tables avec des relations définies entre elles, ce qui facilite l'accès et l'analyse.

- Enregistrements d'entretiens issus d'une étude de marché: ces données sont généralement non structurées, car elles peuvent être sous forme de texte libre, d'audio ou de vidéo, et ne suivent pas un format rigide.

-----

**Exercice 7 : Exercice de transformation**

- Une série d'articles de blog sur les expériences de voyage:

*La methode de transformation que je choisirais pour ce type de données serait la transformation de texte en données structurées. Cela pourrait impliquer l'extraction de mots-clés, la catégorisation des articles par destination ou thème, et la création d'une base de données avec des champs tels que le titre, l'auteur, la date de publication et les destinations mentionnées.*

- Enregistrements audio des appels au service client:

Pour les enregistrements audio des appels au service client, je choisirais la transformation de la parole en texte (speech-to-text) pour convertir les enregistrements audio en données textuelles structurées parce que cela permettrait d'analyser le contenu des appels, d'identifier les problèmes récurrents, de mesurer la satisfaction des clients et de générer des rapports basés sur les interactions avec les clients.

- Notes manuscrites issues d'une séance de brainstorming:

*Pour les notes manuscrites issues d'une séance de brainstorming, je choisirais la transformation de l'écriture manuscrite en texte pour convertir les notes manuscrites en données textuelles structurées. Cela permettrait de faciliter la recherche, l'organisation et l'analyse des idées générées lors de la séance de brainstorming.*

- Un tutoriel vidéo sur la cuisine:

Ici je choisirais la transformation de la vidéo en texte pour extraire les instructions de cuisine, les ingrédients et les étapes de préparation à partir du contenu vidéo. Cela permettrait de créer une recette structurée et facilement accessible pour les utilisateurs qui préfèrent lire plutôt que regarder une vidéo.

---------

**Exercice 8 : Importer un fichier depuis Kaggle**

In [2]:
# importer pandas
import pandas as pd

In [ ]:
# Importez le jeu de données d'entraînement train.csv.
train = pd.read_csv("train.csv")

In [4]:
# Imprimez les premières lignes du DataFrame
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

-----

**Exercice 9 : Exporter un dataframe au format Excel et au format JSON**

In [11]:
# Créez un dataframe simple

data = {
    'Nom': ['Alice', 'Bob', 'Charlie'],
    'Âge': [25, 30, 35],
    'Ville': ['Paris', 'Londres', 'New York']
}

df = pd.DataFrame(data)

In [20]:
# Exportez le dataframe vers un fichier Excel

df.to_csv('exercice9.csv', index=False)

In [ ]:
# Exportez le dataframe vers un fichier json

df.to_json('exercice9.json')

------

**Exercice 10 : Lecture de données JSON**

In [21]:
# importer pandas
import pandas as pd

In [23]:
# Importez les données JSON

df_json = pd.read_json('posts.json')

In [24]:
# Utilisez Pandas pour lire les données JSON

df_json.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...